/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_gui_remake;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author basil
 */
public class Add_Drug_Page extends javax.swing.JFrame {

    /**
     * Creates new form Add_Drug_Page
     */
    public Add_Drug_Page() {
        initComponents();
    }
   /* 
    public void combobox_method(){
        try{
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/milestone2_ver5?zeroDateTimeBehavior=convertToNull","root","pass123");
        Statement stm = connect.createStatement();
        String sql_query="select name from company";
        ResultSet myresult = stm.executeQuery(sql_query);
        
        while (myresult.next()){
            String name=myresult.getString("name");
            company_combobox.addItem(name);
        }
        stm.close();
        connect.close();
        }
        catch(Exception er){
            System.out.println(er.getMessage());
        }
    }
    */
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        drug_name_textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        drug_id_textfield = new javax.swing.JTextField();
        drug_type_textfield = new javax.swing.JTextField();
        drug_barcode_textfield = new javax.swing.JTextField();
        drug_selling_price_textfield = new javax.swing.JTextField();
        drug_production_date_textfield = new javax.swing.JTextField();
        drug_expiration_date_textfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        quantity_counter = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        drug_dose_textfield = new javax.swing.JTextField();
        empty_errorLlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Drug Page");
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(drug_name_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, 20));

        jLabel3.setText("Drug_Id : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel4.setText("BarCode :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 220, -1, -1));

        jLabel5.setText("Type : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 190, -1, -1));

        jLabel6.setText("Selling_Price :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 250, -1, -1));

        jLabel8.setText("Production_Date :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 100, 110, -1));

        jLabel9.setText("Expiration_Date : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel10.setText("Quantity : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 160, -1, -1));
        jPanel1.add(drug_id_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 100, 20));
        jPanel1.add(drug_type_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, 20));
        jPanel1.add(drug_barcode_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 100, 20));
        jPanel1.add(drug_selling_price_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 100, 20));
        jPanel1.add(drug_production_date_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 100, 20));
        jPanel1.add(drug_expiration_date_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 100, 20));

        jLabel1.setBackground(new java.awt.Color(140, 240, 240));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/medicine-bill-resized.png"))); // NOI18N
        jLabel1.setText("Add Drug");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 240, 70));

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/add-resize.png"))); // NOI18N
        add_button.setText("Add");
        add_button.setPreferredSize(new java.awt.Dimension(57, 25));
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 90, -1));

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 90, -1));

        jLabel2.setText("Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        quantity_counter.setModel(new javax.swing.SpinnerNumberModel());
        jPanel1.add(quantity_counter, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 50, 20));

        jLabel12.setText("Dose : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 160, -1, -1));
        jPanel1.add(drug_dose_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 100, 20));
        jPanel1.add(empty_errorLlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 620, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Admin_Page_Remake Adminpage = new Admin_Page_Remake();
        Adminpage.setLocationRelativeTo(this);
        Adminpage.show();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
       Products myproduct = new Products();
       myproduct.name=drug_name_textfield.getText();
       myproduct.type=drug_type_textfield.getText();
       myproduct.barcode=drug_barcode_textfield.getText();
       myproduct.dose=drug_dose_textfield.getText();
       String id_string=drug_id_textfield.getText();
       String price_string=drug_selling_price_textfield.getText();
       myproduct.production_data=drug_production_date_textfield.getText();
       myproduct.expiration_date=drug_expiration_date_textfield.getText();
       String quantity_string=quantity_counter.getValue().toString();
     
       
        if(drug_name_textfield.getText().isEmpty()||drug_type_textfield.getText().isEmpty()
                ||drug_barcode_textfield.getText().isEmpty()||drug_dose_textfield.getText().isEmpty()
                ||drug_id_textfield.getText().isEmpty()||drug_selling_price_textfield.getText().isEmpty()
                ||drug_production_date_textfield.getText().isEmpty()||drug_expiration_date_textfield.getText().isEmpty()
                ){
            empty_errorLlabel.setText("Sorry.. You Should Fill All information");
        }
       else{
       myproduct.product_id=Integer.parseInt(id_string);
       myproduct.selling_price=Double.valueOf(price_string);
       myproduct.quantity=Integer.parseInt(quantity_string);
        try{
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/milestone2_ver5?zeroDateTimeBehavior=convertToNull","root","pass123");
        Statement stm = connect.createStatement(); 
        String sql_query="INSERT INTO PRODUCTS VALUES('"+myproduct.name+"' , '"+myproduct.type+"' , '"+myproduct.barcode+"' , '"
                +myproduct.dose+"' , "+myproduct.product_id+" , "+myproduct.selling_price+" , '"+myproduct.production_data+"' , '"+myproduct.expiration_date+
                "' , "+myproduct.quantity+")";
                
        stm.executeUpdate(sql_query);
        
        JOptionPane.showMessageDialog(this,"Product Has Insert Successfully!");
        
        stm.close();
        connect.close();
        }
        catch(Exception er){
            JOptionPane.showMessageDialog(this,er.getMessage());
        }
               }
        
        
    }//GEN-LAST:event_add_buttonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Drug_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Drug_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Drug_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Drug_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Drug_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton back_button;
    private javax.swing.JTextField drug_barcode_textfield;
    private javax.swing.JTextField drug_dose_textfield;
    private javax.swing.JTextField drug_expiration_date_textfield;
    private javax.swing.JTextField drug_id_textfield;
    private javax.swing.JTextField drug_name_textfield;
    private javax.swing.JTextField drug_production_date_textfield;
    private javax.swing.JTextField drug_selling_price_textfield;
    private javax.swing.JTextField drug_type_textfield;
    private javax.swing.JLabel empty_errorLlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner quantity_counter;
    // End of variables declaration//GEN-END:variables
}
