/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_gui_remake;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author basil
 */
public class Admin_Page_Remake extends javax.swing.JFrame {

    /**
     * Creates new form _Page_Remake
     */
    public Admin_Page_Remake() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        delete_drug_button = new javax.swing.JButton();
        UpdateDrugButton = new javax.swing.JButton();
        add_drug_page_button = new javax.swing.JButton();
        orders_page_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(140, 240, 240));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/settings-resized.png"))); // NOI18N
        jLabel1.setText("Admin Page");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 240, 70));

        jPanel1.setBackground(new java.awt.Color(235, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete_drug_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete_drug_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/delete-resize.png"))); // NOI18N
        delete_drug_button.setText(" Delete Drug");
        delete_drug_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_drug_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(delete_drug_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 190, 30));

        UpdateDrugButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateDrugButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/updating-resize.png"))); // NOI18N
        UpdateDrugButton.setText(" Update Drug");
        UpdateDrugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDrugButtonActionPerformed(evt);
            }
        });
        jPanel2.add(UpdateDrugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 30));

        add_drug_page_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_drug_page_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/add-resize.png"))); // NOI18N
        add_drug_page_button.setText(" Add Drug");
        add_drug_page_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_drug_page_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(add_drug_page_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 190, 30));

        orders_page_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orders_page_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/shopping-onebag-resized.png"))); // NOI18N
        orders_page_button.setText("Show Orders");
        orders_page_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orders_page_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(orders_page_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 230, 200));

        jPanel3.setBackground(new java.awt.Color(235, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/medicineresized.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, 160));

        logout_button.setText("Log Out");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_drug_page_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_drug_page_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Add_Drug_Page add_page = new Add_Drug_Page(); 
        add_page.setLocationRelativeTo(this);
        add_page.show();
    }//GEN-LAST:event_add_drug_page_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Log_In_Page_Remake page1 = new Log_In_Page_Remake();
        page1.setLocationRelativeTo(this);
        page1.show();
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void delete_drug_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_drug_buttonActionPerformed
        // TODO add your handling code here:
        Products myproduct = new Products();
        String drug_id_string=JOptionPane.showInputDialog("Enter Drug Id to Delete : ");
        myproduct.product_id=Integer.parseInt(drug_id_string);
        try{
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/milestone2_ver5?zeroDateTimeBehavior=convertToNull","root","pass123");
        Statement stm = connect.createStatement();
        String sql_query="SELECT Product_id FROM PRODUCTS WHERE Product_id="+myproduct.product_id+";";
        String sql_delete="DELETE FROM PRODUCTS WHERE Product_id="+myproduct.product_id+";";
        ResultSet myresult = stm.executeQuery(sql_query);
        if(myresult.next()){
        stm.executeUpdate(sql_delete);
        JOptionPane.showMessageDialog(this,"Drug has Delete it succseefully!");
        }
        else{
           JOptionPane.showMessageDialog(this,"Not Found..."); 
        }
        stm.close();
        connect.close();
        }
        catch(Exception er){
            System.out.println(er.getMessage());
        }
       
    }//GEN-LAST:event_delete_drug_buttonActionPerformed

    private void UpdateDrugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDrugButtonActionPerformed
        dispose();
        Update_Drug_Page updateDrug = new Update_Drug_Page();
        updateDrug.setLocationRelativeTo(this);
        updateDrug.show();
    }//GEN-LAST:event_UpdateDrugButtonActionPerformed

    private void orders_page_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orders_page_buttonActionPerformed
            dispose();
            Show_orders_page OrderPage = new Show_orders_page();
            OrderPage.setLocationRelativeTo(this);
            OrderPage.show();
    }//GEN-LAST:event_orders_page_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Page_Remake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateDrugButton;
    private javax.swing.JButton add_drug_page_button;
    private javax.swing.JButton delete_drug_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton orders_page_button;
    // End of variables declaration//GEN-END:variables
}
