/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_gui_remake;

import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author basil
 */
public class Adminstrator_Registration_page extends javax.swing.JFrame {

    /**
     * Creates new form Adminstrator_Registration_page
     */
    public Adminstrator_Registration_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        register_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        ssn_textfield = new javax.swing.JTextField();
        fullname_textfield = new javax.swing.JTextField();
        dob_textfield = new javax.swing.JTextField();
        gender_combobox = new javax.swing.JComboBox<>();
        salary_textfield = new javax.swing.JTextField();
        address_textfield = new javax.swing.JTextField();
        phone_textfield = new javax.swing.JTextField();
        password_textfield = new javax.swing.JPasswordField();
        confirm_textfield = new javax.swing.JPasswordField();
        empty_errorLlabel = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adminstrator Registration Page");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/user-resized.png"))); // NOI18N
        jLabel1.setText("Adminstrator Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 270, -1));

        jLabel2.setText("SSN :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel3.setText("Full Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 110, -1, -1));

        jLabel4.setText("DOB :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 140, -1, 20));

        jLabel6.setText("Gender :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 170, -1, -1));

        jLabel7.setText("Address :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 80, -1, -1));

        jLabel8.setText("Phone :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 110, -1, -1));

        jLabel9.setText("Password : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel10.setText("Confirm Passwod :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 170, -1, -1));

        jLabel11.setText("Salary :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        register_button.setText("Register");
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        cancel_button.setText("Cancel");
        cancel_button.setMaximumSize(new java.awt.Dimension(75, 25));
        cancel_button.setMinimumSize(new java.awt.Dimension(75, 25));
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));
        jPanel1.add(ssn_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 90, 20));
        jPanel1.add(fullname_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, 20));
        jPanel1.add(dob_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 90, -1));

        gender_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(gender_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 20));
        jPanel1.add(salary_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 20));
        jPanel1.add(address_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 90, 20));
        jPanel1.add(phone_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 20));
        jPanel1.add(password_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 90, 20));
        jPanel1.add(confirm_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 90, 20));
        jPanel1.add(empty_errorLlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO add your handling code here:
        Adminstrator admin_account=new Adminstrator();
        String ssn_string=ssn_textfield.getText();
        admin_account.name=fullname_textfield.getText();
        admin_account.dob=dob_textfield.getText();
        admin_account.gender=gender_combobox.getSelectedItem().toString();
        admin_account.address=address_textfield.getText();
        String phone_string=phone_textfield.getText();
        admin_account.password=password_textfield.getPassword().toString();
        String salary_string=salary_textfield.getText();
        String mypassword=new String(password_textfield.getPassword());
        String mypassword2=new String(confirm_textfield.getPassword());
       
        if(ssn_textfield.getText().isEmpty()||fullname_textfield.getText().isEmpty()
                ||dob_textfield.getText().isEmpty()||address_textfield.getText().isEmpty()
                ||phone_textfield.getText().isEmpty()||password_textfield.getText().isEmpty()
                ||salary_textfield.getText().isEmpty()||confirm_textfield.getText().isEmpty()){
            empty_errorLlabel.setText("Sorry.. You Should Fill All information");
        }
        else{
            if(mypassword.equals(mypassword2)){
            admin_account.SSN=new BigInteger(ssn_string);
            admin_account.phone=Integer.parseInt(phone_string);
            admin_account.salary=Integer.parseInt(salary_string);
            try{
            Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/milestone2_ver5?zeroDateTimeBehavior=convertToNull","root","pass123");
            Statement stm = connect.createStatement(); 
            String sql_query="INSERT INTO ADMINSTRATOR VALUES("+admin_account.SSN+",'"+admin_account.name+"','"+
              admin_account.dob+"','"+admin_account.gender+"','"+admin_account.address+"',"+admin_account.phone+",'"+
              mypassword+"',"+admin_account.salary+")";
            
            String sql_query2="INSERT INTO ADMIN_LOGIN VALUES("+admin_account.SSN+",'"+mypassword+"')";
            
            stm.executeUpdate(sql_query);
            stm.executeUpdate(sql_query2);
            
            JOptionPane.showMessageDialog(this,"Account Has Created Successfully!");
            
            stm.close();
            connect.close();
            
            }
            catch(Exception er){
                System.out.println(er.getMessage());
            }
            }
            else{
                empty_errorLlabel.setText("Password Isn't Identical");
            }
        }
    }//GEN-LAST:event_register_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminstrator_Registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminstrator_Registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminstrator_Registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminstrator_Registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminstrator_Registration_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_textfield;
    private javax.swing.JButton cancel_button;
    private javax.swing.JPasswordField confirm_textfield;
    private javax.swing.JTextField dob_textfield;
    private javax.swing.JLabel empty_errorLlabel;
    private javax.swing.JTextField fullname_textfield;
    private javax.swing.JComboBox<String> gender_combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_textfield;
    private javax.swing.JTextField phone_textfield;
    private javax.swing.JButton register_button;
    private javax.swing.JTextField salary_textfield;
    private javax.swing.JTextField ssn_textfield;
    // End of variables declaration//GEN-END:variables
}
