/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_gui_remake;

/**
 *
 * @author basil
 */
public class Customer_Page_Remake extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Page_Remake
     */
    public Customer_Page_Remake() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        available_Page_button = new javax.swing.JButton();
        Order_page_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        invoice_page_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Page");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(590, 411));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(140, 240, 240));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/shopping-bag-resized.png"))); // NOI18N
        jLabel1.setText("Customer Page");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 240, 70));

        available_Page_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        available_Page_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/medicine-bill-resized.png"))); // NOI18N
        available_Page_button.setText("Available Drugs");
        available_Page_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                available_Page_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(available_Page_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 190, 30));

        Order_page_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Order_page_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/shopping-onebag-resized.png"))); // NOI18N
        Order_page_button.setText("Purchase Drugs");
        Order_page_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_page_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Order_page_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 165, 190, 30));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invoice_page_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        invoice_page_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bill-resized.png"))); // NOI18N
        invoice_page_button.setText("Show Invoices");
        invoice_page_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoice_page_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(invoice_page_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 125, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 270, 210));

        logout_button.setText("Log Out");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 310, -1, -1));

        jPanel3.setBackground(new java.awt.Color(235, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/medicineresized.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void available_Page_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_available_Page_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        available_drugs_page avpage = new available_drugs_page();
        avpage.setLocationRelativeTo(this);
        avpage.show();
    }//GEN-LAST:event_available_Page_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Log_In_Page_Remake page1 = new Log_In_Page_Remake();
        page1.setLocationRelativeTo(this);
        page1.show();
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void Order_page_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Order_page_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Order_page order = new Order_page();
        order.setLocationRelativeTo(this);
        order.show();
    }//GEN-LAST:event_Order_page_buttonActionPerformed

    private void invoice_page_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoice_page_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        show_invoices_page bill = new show_invoices_page();
        bill.setLocationRelativeTo(this);
        bill.show();
    }//GEN-LAST:event_invoice_page_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Page_Remake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Order_page_button;
    private javax.swing.JButton available_Page_button;
    private javax.swing.JButton invoice_page_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logout_button;
    // End of variables declaration//GEN-END:variables
}
