/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_gui_remake;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author basil
 */
public class Log_In_Page_Remake extends javax.swing.JFrame {

    /**
     * Creates new form Log_In_Page_Remake
     */
    public Log_In_Page_Remake() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username_textfield = new javax.swing.JTextField();
        password_textfield = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Login_button = new javax.swing.JButton();
        Cancel_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Admin_radiobutton = new javax.swing.JRadioButton();
        Customer_radiobutton = new javax.swing.JRadioButton();
        Register_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In Page");
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(112, 218, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/log-inresized.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 400));

        jPanel2.setBackground(new java.awt.Color(235, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/medicineresized.png"))); // NOI18N
        jLabel1.setText("Welcome To Pharmacy System ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 380, 100));

        username_textfield.setBackground(new java.awt.Color(235, 255, 255));
        username_textfield.setText("UserName");
        username_textfield.setBorder(null);
        username_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_textfieldFocusGained(evt);
            }
        });
        username_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_textfieldActionPerformed(evt);
            }
        });
        jPanel2.add(username_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 200, -1));

        password_textfield.setBackground(new java.awt.Color(235, 255, 255));
        password_textfield.setText("Password");
        password_textfield.setBorder(null);
        password_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_textfieldFocusGained(evt);
            }
        });
        password_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_textfieldKeyPressed(evt);
            }
        });
        jPanel2.add(password_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, -1));

        jLabel3.setText("_________________________");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 200, -1));

        jLabel4.setText("_________________________");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, -1));

        Login_button.setText("Log In");
        Login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_buttonActionPerformed(evt);
            }
        });
        Login_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Login_buttonKeyPressed(evt);
            }
        });
        jPanel2.add(Login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        Cancel_button.setText("Cancel");
        Cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(Cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/padlock-resized.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/user-resized.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        Admin_radiobutton.setBackground(new java.awt.Color(235, 255, 255));
        buttonGroup1.add(Admin_radiobutton);
        Admin_radiobutton.setSelected(true);
        Admin_radiobutton.setText("Admin");
        jPanel2.add(Admin_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Customer_radiobutton.setBackground(new java.awt.Color(235, 255, 255));
        buttonGroup1.add(Customer_radiobutton);
        Customer_radiobutton.setText("Customer");
        jPanel2.add(Customer_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        Register_button.setText("Register");
        Register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(Register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 550, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void username_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_textfieldActionPerformed

    private void Login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_buttonActionPerformed
        // TODO add your handling code here:
        try{
            Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/milestone2_ver5?zeroDateTimeBehavior=convertToNull","root","pass123");
            Statement stm = connect.createStatement();
            //O File
            File myfile = new File("UserId.txt");
            FileWriter filewriter = new FileWriter(myfile);
            PrintWriter printwriter = new PrintWriter(filewriter);
            
            String username=username_textfield.getText(); 
            String password=password_textfield.getText();
            if(Admin_radiobutton.isSelected()){
                String sql_query="SELECT * FROM ADMIN_LOGIN WHERE ADMIN_SSN='"+username+"' AND PASSWORD='"+password+"'";
                ResultSet myresult=stm.executeQuery(sql_query);
                
                if(myresult.next()){
                    printwriter.print(myresult.getString(1));
                    printwriter.close();
                    dispose();
                    Admin_Page_Remake Adminpage = new Admin_Page_Remake();
                    Adminpage.setLocationRelativeTo(this);
                    Adminpage.show();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Sorry..Username or Password Is Wrong", "Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(Customer_radiobutton.isSelected()){
                String sql_query="SELECT * FROM CUSTOMER_LOGIN WHERE CUST_ID='"+username+"' AND CUST_PASSWORD='"+password+"'";
                ResultSet myresult=stm.executeQuery(sql_query);
                
                if(myresult.next()){
                    printwriter.print(myresult.getString(1));
                    printwriter.close();
                    dispose();
                    Customer_Page_Remake custpage = new Customer_Page_Remake();
                    custpage.setLocationRelativeTo(this);
                    custpage.show();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Sorry..Username or Password Is Wrong", "Erore",JOptionPane.ERROR_MESSAGE);
                }
            }
             stm.close();
            connect.close();
        }
        catch(Exception er){
            System.out.println(er.getMessage());
        }
        
    }//GEN-LAST:event_Login_buttonActionPerformed

    private void Cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_buttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Cancel_buttonActionPerformed

    private void Register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_buttonActionPerformed
        // TODO add your handling code here:
        Choose_account_page choose_page = new Choose_account_page();
        choose_page.setLocationRelativeTo(this);
        choose_page.show();
    }//GEN-LAST:event_Register_buttonActionPerformed

    private void username_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_textfieldFocusGained
        username_textfield.setText("");
    }//GEN-LAST:event_username_textfieldFocusGained

    private void password_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_textfieldFocusGained
        password_textfield.setText("");
    }//GEN-LAST:event_password_textfieldFocusGained

    private void Login_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Login_buttonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_buttonKeyPressed

    private void password_textfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_textfieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
        try{
            Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/milestone2_ver5?zeroDateTimeBehavior=convertToNull","root","pass123");
            Statement stm = connect.createStatement();
            //O File
            File myfile = new File("UserId.txt");
            FileWriter filewriter = new FileWriter(myfile);
            PrintWriter printwriter = new PrintWriter(filewriter);
            
            String username=username_textfield.getText(); 
            String password=password_textfield.getText();
            if(Admin_radiobutton.isSelected()){
                String sql_query="SELECT * FROM ADMIN_LOGIN WHERE ADMIN_SSN='"+username+"' AND PASSWORD='"+password+"'";
                ResultSet myresult=stm.executeQuery(sql_query);
                
                if(myresult.next()){
                    printwriter.print(myresult.getString(1));
                    printwriter.close();
                    dispose();
                    Admin_Page_Remake Adminpage = new Admin_Page_Remake();
                    Adminpage.setLocationRelativeTo(this);
                    Adminpage.show();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Sorry..Username or Password Is Wrong", "Erore",JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(Customer_radiobutton.isSelected()){
                String sql_query="SELECT * FROM CUSTOMER_LOGIN WHERE CUST_ID='"+username+"' AND CUST_PASSWORD='"+password+"'";
                ResultSet myresult=stm.executeQuery(sql_query);
                
                if(myresult.next()){
                    printwriter.print(myresult.getString(1));
                    printwriter.close();
                    dispose();
                    Customer_Page_Remake custpage = new Customer_Page_Remake();
                    custpage.setLocationRelativeTo(this);
                    custpage.show();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Sorry..Username or Password Is Wrong", "Error",JOptionPane.ERROR_MESSAGE);
                }
            }
             stm.close();
            connect.close();
        }
        catch(Exception er){
            System.out.println(er.getMessage());
        }
        }
    }//GEN-LAST:event_password_textfieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_In_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_In_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_In_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_In_Page_Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_In_Page_Remake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Admin_radiobutton;
    private javax.swing.JButton Cancel_button;
    private javax.swing.JRadioButton Customer_radiobutton;
    private javax.swing.JButton Login_button;
    private javax.swing.JButton Register_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password_textfield;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
