/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_gui_remake;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author basil
 */
public class Show_orders_page extends javax.swing.JFrame {

    /**
     * Creates new form Show_orders_page
     */
    public Show_orders_page() {
        initComponents();
        show_allOrders("SELECT * FROM ORDERS");
    }
    
    public void show_allOrders(String query){
        
        try{
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/milestone2_ver5?zeroDateTimeBehavior=convertToNull","root","pass123");
        Statement stm = connect.createStatement();
        ResultSet myresult=stm.executeQuery(query);
        ResultSetMetaData mymetadata=myresult.getMetaData();
        DefaultTableModel mymodel=(DefaultTableModel) orders_jtable.getModel();
        mymodel.setRowCount(0);
        int columns_num=mymetadata.getColumnCount();
        String[] columns_name = new String[columns_num];
            
        for(int i=0;i<columns_num;i++){
            columns_name[i]=mymetadata.getColumnName(i+1);
        }
        mymodel.setColumnIdentifiers(columns_name);
        
        Order myorder = new Order();
        while(myresult.next()){
            String order_id=myresult.getString(1);
            myorder.cust_id=myresult.getString(2);
            myorder.cust_name=myresult.getString(3);
            myorder.product_id=myresult.getString(4);
            myorder.product_name=myresult.getString(5);
            myorder.quantity=myresult.getString(6);
            myorder.price=myresult.getString(7);
            myorder.order_date=myresult.getString(8);
            
            String []row={order_id,myorder.cust_id,myorder.cust_name,myorder.product_id,
                            myorder.product_name,myorder.quantity,myorder.price,myorder.order_date};
            mymodel.addRow(row);
        }
        stm.close();
        connect.close();
        }
        catch(Exception er){
            System.out.println(er.getMessage());
        }
    }
    
    public void sorting_acs_desc(){
        if(sort_word_box.getSelectedItem()=="order id"&&asc_radiobutton.isSelected()){
            show_allOrders("SELECT * FROM ORDERS ORDER BY Order_ID");
        }
            else if(sort_word_box.getSelectedItem()=="order id"&&desc_radiobutton.isSelected()){
            show_allOrders("SELECT * FROM ORDERS ORDER BY Order_ID DESC");
            }
            
            else if(sort_word_box.getSelectedItem()=="Quantity"&&asc_radiobutton.isSelected()){
               show_allOrders("SELECT * FROM ORDERS ORDER BY QUANTITY"); 
            }
            else if(sort_word_box.getSelectedItem()=="Quantity"&&desc_radiobutton.isSelected()){
               show_allOrders("SELECT * FROM ORDERS ORDER BY QUANTITY DESC"); 
            }
            
            else if(sort_word_box.getSelectedItem()=="Price"&&asc_radiobutton.isSelected()){
                show_allOrders("SELECT * FROM ORDERS ORDER BY price");
            }
            else if(sort_word_box.getSelectedItem()=="Price"&&desc_radiobutton.isSelected()){
                show_allOrders("SELECT * FROM ORDERS ORDER BY price DESC");
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orders_jtable = new javax.swing.JTable();
        back_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sort_word_box = new javax.swing.JComboBox<>();
        asc_radiobutton = new javax.swing.JRadioButton();
        desc_radiobutton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Orders Page");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/shopping-onebag-resized.png"))); // NOI18N
        jLabel1.setText("All Orders");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, -1));

        orders_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(orders_jtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 660, 140));

        back_button.setText("Back");
        back_button.setToolTipText("");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sort Orders By : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        sort_word_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "order id", "Quantity", "Price" }));
        sort_word_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sort_word_boxItemStateChanged(evt);
            }
        });
        jPanel1.add(sort_word_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        asc_radiobutton.setBackground(new java.awt.Color(235, 255, 255));
        buttonGroup1.add(asc_radiobutton);
        asc_radiobutton.setSelected(true);
        asc_radiobutton.setText("Ascending");
        asc_radiobutton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                asc_radiobuttonItemStateChanged(evt);
            }
        });
        jPanel1.add(asc_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        desc_radiobutton.setBackground(new java.awt.Color(235, 255, 255));
        buttonGroup1.add(desc_radiobutton);
        desc_radiobutton.setText("Descending ");
        desc_radiobutton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                desc_radiobuttonItemStateChanged(evt);
            }
        });
        jPanel1.add(desc_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Admin_Page_Remake Adminpage = new Admin_Page_Remake();
        Adminpage.setLocationRelativeTo(this);
        Adminpage.show();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void sort_word_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sort_word_boxItemStateChanged
        // TODO add your handling code here:
        try{
        if(evt.getStateChange()==ItemEvent.SELECTED){
            sorting_acs_desc();
        }
        }
        catch(Exception er){
            System.out.println(er.getMessage());
        }
    }//GEN-LAST:event_sort_word_boxItemStateChanged

    private void asc_radiobuttonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_asc_radiobuttonItemStateChanged
        // TODO add your handling code here:
         try{
        if(evt.getStateChange()==ItemEvent.SELECTED){
            sorting_acs_desc();
        }
        }
        catch(Exception er){
            System.out.println(er.getMessage());
        }
        
    }//GEN-LAST:event_asc_radiobuttonItemStateChanged

    private void desc_radiobuttonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_desc_radiobuttonItemStateChanged
        // TODO add your handling code here:
        try{
        if(evt.getStateChange()==ItemEvent.SELECTED){
            sorting_acs_desc();
        }
        }
        catch(Exception er){
            System.out.println(er.getMessage());
        }
    }//GEN-LAST:event_desc_radiobuttonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_orders_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_orders_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_orders_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_orders_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_orders_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton asc_radiobutton;
    private javax.swing.JButton back_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton desc_radiobutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orders_jtable;
    private javax.swing.JComboBox<String> sort_word_box;
    // End of variables declaration//GEN-END:variables
}
